config/routes.rb
Tbsample::Application.routes.draw do
  root :to => 'setofsubyears#index'
  
  match 'auth/:provider/callback' => 'sessions#create'
  match '/logout' => 'sessions#destroy', :as => :logout
  match '/my' => 'sessions#mypage', :as => :mypage

  match 'q/:subject/:year' => 'questions#index'
  match 'q/:subject/:year/:number' => 'questions#show'
  match 'q/:subject/:year/:number/ans/:answer' => 'questions#answer'
  match 'theme/:themecode' => 'themes#index'

  match 'q/:subject/:year/:number/c' => 'comments#index', :via => :get
  match 'q/:subject/:year/:number/c' => 'comments#create', :via => :post, :as => 'question_comments'
  match 'q/:subject/:year/:number/c/new' => 'comments#new'
  match 'q/:subject/:year/:number/c/:id/edit' => 'comments#edit'
  match 'q/:subject/:year/:number/c/:id' => 'comments#update', :via => :put
  match 'q/:subject/:year/:number/c/:id' => 'comments#destroy', :via => :delete

  post 'api/memo' => 'api#set_memo', :as => 'set_memo'
  get 'api/memo' => 'api#get_memo', :as => 'get_memo'

  

end

app/models/question.rb
# coding: utf-8
class Question < ActiveRecord::Base
  attr_accessible :answer, :number, :pdf, :png, :selectioncount, :subquestion, :svg, :themecode, :subject, :year
  has_many :comments
  has_many :answer_logs

  def self.to_kamoku(subject_code)
    { 
      'a' => '経済学・経済政策',
      'b' => '財務・会計',
      'c' => '企業経営理論',
      'd' => '運営管理',
      'e' => '経営法務',
      'f' => '経営情報システム',
      'g' => '中小企業経営・政策',
    }[subject_code]
  end

  def self.to_subject_code_by_themecode(themecode)
    [nil, 'a', 'b', 'c', 'd', 'e', 'f', 'g'][themecode[0].to_i]
  end

  def subject_code
    Question.to_subject_code_by_themecode(self.themecode)
  end

  def kamoku
    Question.to_kamoku(self.subject_code)
  end

  def maintheme
    Theme.where(themecode: self.themecode).first.maintheme
  end

  def subtheme
    Theme.where(themecode: self.themecode).first.subtheme
  end

  def next
    Question.where(subject: self.subject, year: self.year, number: (self.number)+1).first
  end
  
  def prev
    Question.where(subject: self.subject, year: self.year, number: (self.number)-1).first
  end

  def history(user)
    if user
      user.answer_logs.where(question_id: self.id).limit(3)
    else
      []
    end
  end

  def last3count(user)
    # hist =  user.answer_logs.where(question_id: self.id).limit(3).group(:correct).size
    # hist[true] ||= 0
    # hist[false] ||= 0
    # hist
     history(user).map{|h|h.correct}.inject(Hash.new(0)){|acc,item|acc[item]+=1;acc}
  end

  def last3status(user) #info(lightblue), success(green), error(red)
    t = last3count(user)[true]
    f = last3count(user)[false]
    
    if (t==0) && (f==0)
      ""
    elsif ((t==2) && (f==0)) || t==3 
      "info"
    elsif t > f
      "success"
    else
      "error"
    end 
  end

  def code
    "#{self.subject}/#{self.year}/#{"%02d" % self.number}"
  end

  def self.find_by_code(code)
    subject, year, number = code.split('/')
    Question.where(subject: subject, year: year.to_i, number: number.to_i).first
  end

end

app/controllers/questions_controller.rb
# coding: utf-8
class QuestionsController < ApplicationController

  Kamoku = { 
    'a'=> "経済学・経済政策",
    'b'=> "財務・会計",
    'c'=> "企業経営理論", 
    'd'=> "運営管理",
    'e'=> "経営法務", 
    'f'=> "経営情報システム", 
    'g'=> "中小企業経営・政策"
  }

  def index #/q/:subject/:year
    @subject = params[:subject]
    @kamoku = Kamoku[@subject]
    @year = params[:year]
    @qnum = params[:number]
    @questions = Question.where(subject: @subject, year: @year).all
    @themes = []
    @questions.each do |q|
      @themes[q.number] = Theme.where(themecode: q.themecode).first
    end
  end

  def show #/q/:subject/:year/:number
    @subject = params[:subject]
    @kamoku = Kamoku[@subject]
    @year = params[:year]
    @qnum = params[:number]
    @question = Question.where(subject: @subject, year: @year, number: @qnum).first
    @theme = Theme.where(themecode: @question.themecode).first
    @themequestions = Question.where(themecode: @question.themecode).all
    
    @comment = @question.comments.build
  end

  def answer
    @subject = params[:subject]
    @kamoku = Kamoku[@subject]
    @year = params[:year]
    @qnum = params[:number]
    @answer = params[:answer]
    @section_num = @answer.count(',') # 複数設問対応
    @question = Question.where(subject: @subject, year: @year, number: @qnum).first
    @right = @question.answer.split(',')[@section_num]
    @answer.delete!(',')
    @correct = if @answer == '*'
                 true
               else
                 @answer == @right
               end
    # user = session[:user_id] ? User.find(session[:user_id]) : nil
    AnswerLog.create(question_id: @question.id, user_id: session[:user_id], correct: @correct, section_num: @section_num, choose: @answer)
    render json: { answer: @answer, correct: @correct, right: @right, section: @section_num }
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/index.html.erb
<ul class="breadcrumb">
    <li><%= link_to 'Home', '/' %><span class="divider">/</span></li>
    <li class="active"><%= @year %>年度 <%= @kamoku %></li>
</ul>

<h4><%= @year %>年度 <%= @kamoku %></h4>
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <% if current_user %>
                <th>履歴</th>
            <% end %>
            <th>問数</th>
            <th>テーマ</th>
            <th>サブテーマ</th>
        </tr>
    </thead>
    <tbody>
        <% @questions.each do |q| %>
                <% if current_user %>
                    <% table_class = q.last3status(current_user) %>
                    <tr style="cursor: pointer" class="<%= table_class %>" data-href=<%= "/q/#{@subject}/#{q.year}/#{q.number}" %>> 
                    <td>
                        <span style="white-space: nowrap">
                            <% q.history(current_user).each do |h| %>
                                <% if h.correct %>
                                    <span class="right">◯</span>
                                <% else %>
                                    <span class="wrong">×</span>
                                <% end %>
                            <% end %>
                        </span>
                    </td>
                <% else %>
                    <tr style="cursor: pointer" data-href=<%= "/q/#{@subject}/#{q.year}/#{q.number}" %>> 
                <% end %>
                <td style="white-space: nowrap">
                    <%= link_to "第#{q.number}問","/q/#{@subject}/#{q.year}/#{q.number}" %>
                </td>
                <td><%= abbifsmapho q.maintheme %></td>
                <td><%= abbifsmapho q.subtheme %></td>
            </tr>
        </a>
    <% end %>
    </tbody>
</table>

<script>
    jQuery( function($) {
        $('tbody tr[data-href]').addClass('clickable').click( function() {
            window.location = $(this).attr('data-href');
            }).find('a').hover( function() {
            $(this).parents('tr').unbind('click');
            }, function() {
            $(this).parents('tr').click( function() {
                window.location = $(this).attr('data-href');
            });
        });
    });
</script>

<% if false %>
<ul class="thumbnails">
    <% @questions.each do |q| %>
        <li class="span3">
        <div class="thumbnail">
            <%= link_to (image_tag "/assets/svg/#{q.svg}", height:"100"), "/q/#{@subject}/#{q.year}/#{q.number}" %>
            <!-- <%= (image_tag "/assets/svg/#{q.svg}", height:"100") %> -->
            <div class="caption">
                <h5>第<%= q.number %>問</h5>
                <%= @themes[q.number].subtheme %>
            </div>
        </div>
        </li>
    <% end %>
</ul>
<% end %>
<%= link_to 'Topへ', '/' %>

app/views/questions/show.html.erb
<% content_for :meta_tag do
    set_meta_tags :site => '中小企業診断士の過去問',
        :description => "#{@theme.maintheme} #{@theme.subtheme}",
        :keywords => ['過去問', '診断士', 'テーマ別', @kamoku],
        :title => "#{@year}年度#{@kamoku} 第#{@question.number}問",
        :reverse => true,
        :open_graph => {
            :site_name => '中小企業診断士の過去問',
            :title => "#{@year}年度#{@kamoku} 第#{@question.number}問",
            :description => "#{@theme.maintheme} #{@theme.subtheme}",
            :url => request.url,
            :type => 'website',
            :image => 'http://smec-kakomon.jp/assets/logo2.png'
        }
%>
<%= display_meta_tags %>
<% end %>

<% content_for :sidebar do %>
    <div class="sbox">
        <h2>自分用メモ</h2>
        <div class="sboxInner">
            <% if current_user %>
                <textarea 
                    class="memoBox" 
                    id="memo" 
                    placeholder="このメモは他の人には公開されません。"></textarea>
                <button 
                    id="memo_save_button" 
                    class="btn small" 
                    style="line-height:12px"
                    data-remote="true">
                    内容を保存する</button>
                <span 
                    class="label label-success"
                    id="memo_sysmessage" 
                    style="display:none"
                    >保存しました</span>
            <% else %>
                <p>ログインすると、問題ごとに自分専用のメモが残せます。</p>
            <% end %>
        </div>

    </div>
<% end %>

<ul class="breadcrumb">
    <li><%= link_to 'Home', '/' %><span class="divider">/</span></li>
    <li><%= link_to "#{@year} 年度 #{@kamoku}", "/q/#{@question.subject}/#{@year}" %>
        <span class="divider">/</span></li>
    <li class="active"><%= "第#{@question.number}問" %></li>
</ul>

<h4><%= @year %>年度 <%= @kamoku %></h4>
<table class="table table-bordered">
    <!--
    <thead>
        <tr><th>qnum</th><th>sqnum</th><th>tcode</th><th>svg</th></tr>
    </thead>
    -->
    <tbody>
        <tr><td>
                <%= render partial: "shared/questions", object: @question %>
        </td></tr>
    </tbody>
</table>

<ul class="pager">
    <% p = @question.prev %>
    <% n = @question.next %>
    <li class="previous">
    <% if p %>
        <%= link_to("＜前の問題", "/q/#{p.subject}/#{p.year}/#{p.number}") %>
    <% else %>
        <%= link_to("#{@question.year}年#{@question.kamoku}", "/q/#{@question.subject}/#{@question.year}") %>
    <% end %>
    </li>
    <li class="next">
    <% if n %>
        <%= link_to("次の問題＞", "/q/#{n.subject}/#{n.year}/#{n.number}") %>
    <% else %>
        <%= link_to("#{@question.year}年#{@question.kamoku}", "/q/#{@question.subject}/#{@question.year}") %>
    <% end %>
    </li>
</ul>

<div class="tabbable tabs-top">
    <ul class="nav nav-tabs">
        <li class="active">
        <a href="#kanren" data-toggle="tab">関連情報</a></li>
        <li>
        <a href="#theme" data-toggle="tab">同じテーマの出題状況(<%= @themequestions.count %>)</a>
        </li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active", id="kanren">
            <!--
            <% if @question.comments.any? %>
                <ul>
                    <% @question.comments.each do |c| %>
                        <% if c.id %>
                            <div class="commentBox" id="comment_<%= c.id %>">
                                <div class="commentBoxinner">
                                    <p>
                                    <% c.body.each_line do |l| %>
                                        <%= auto_link(l, html: {target: '_blank'}) %><br>
                                    <% end %>
                                    </p> by <%= c.commenter %>
                                    <% if current_user && (current_user.id == c.user_id) %>
                                        <%= link_to content_tag('i', '', class: 'icon-trash'),
                                            "#{question_path @question}/c/#{c.id}",
                                        confirm: "削除してもよろしいですか？", method: :delete, remote: true %>
                                    <% end %>
                                </div>
                            </div>
                            
                        <% end %>
                    <% end %>
                </ul>
            <% else %>
                <p>関連情報はありません。</p>
            <% end %>

            <% if current_user %>
                <%= form_for( 
                             @question.comments, url: "/q/#{@question.subject}/#{@question.year}/#{@question.number}/c",
                             method: 'POST',
                                 html: {class:'form-horizontal'}
                            ) do |f| %>
                    <% if @comment.errors.any? %>
                        <ul>
                            <% @comment.errors.full_messages.each do |msg| %>
                                <li><%= msg %></li>
                            <% end %>
                        </ul>
                    <% end %>
                    <%= f.hidden_field :user_id, value: current_user.id %>
                    <div class="control-group">
                        <div class="field">
                            <%= f.label :commenter, "名前", class: "control-label" %>
                            <div class="controls">
                                <%= f.text_field :commenter, value: current_user.name %>
                            </div>
                        </div>
                    </div>
                    <div class="control-group">
                        <div class="field">
                            <%= f.label :body, "コメント", class: "control-label"  %>
                            <div class="controls">
                                <%= f.text_area :body, rows: 5 %>
                            </div>
                        </div>
                    </div>
                    <div class="control-group">
                        <div class="controls">
                            <div class="actions">
                                <%= f.submit "送信"%>
                            </div>
                        </div>
                    </div>
                <% end %>
            <% else %>
                <div class="alert alert-info">
                    <button class="close" data-dismiss="alert">&times;</button>
                    コメントを残すには、ログインしてください。
                </div>

            <% end %>
            -->
            <div class="fb-comments" data-href="<%= request.url %>" data-width="470" data-num-posts="10"></div>
        </div>
        <div class="tab-pane", id="theme">
            <p><%= link_to "#{@theme.maintheme}/#{@theme.subtheme}", "/theme/#{@theme.themecode}" %></p>
            <table class="table table-bordered">
                <thead>
                    <tr><td>2012年</td><td>2011年</td><td>2010年</td><td>2009年</td><td>2008年</td></tr>
                </thead>
                <tbody>
                    <tr>
                        <% [2012, 2011, 2010, 2009, 2008].each do |year| %>
                            <td>
                                <% yearqestions = @themequestions.select{|x|x.year==year}.each do |q| %>
                                    <p><%= link_to "第#{q.number}問", "/q/#{q.subject}/#{q.year}/#{q.number}" %></p>
                                <% end %>
                                <%= "-" if yearqestions.empty? %>
                            </td>
                        <% end %>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>


<%= link_to 'Topへ', '/' %>

<script>
    $(function() {
        $('a[data-method="delete"]').live('ajax:success', function(e, data, status, xhr){
           // alert("deleted!");
           $('#comment_' + data.comment.id).fadeOut("slow");
       });

       $('#memo_save_button').click(function(){
          // alert($('#memo').val());
          $.ajax({
              type: 'POST',
              url: '<%= set_memo_path %>',
              data: {
                  user_id: <%= current_user ? current_user.id : "" %>,
                  question: '<%= @question.code %>',
                  body: $('#memo').val(),
              },
              dataType: 'json',
              cache: false,
          })
          .done(function(data){
              if(data.success){
                  // success
                  $('#memo_sysmessage').fadeIn(500, function() {
                      setTimeout(function() {
                          $('#memo_sysmessage').fadeOut(500);
                      }, 1000);
                  });
              } else {
                  alert("コメントの保存に失敗しました。再度試してください。");
              }
          })
          .fail(function(data){
              alert("コメントの保存に失敗しました。再度試してください。");
          });

       }) 
   });  

   jQuery.event.add(window,"load",function(){
       $.ajax({
           type: 'GET',
           url: '<%= get_memo_path %>',
           data: {
               user_id: <%= current_user ?  current_user.id : ""%>,
               question: '<%= @question.code %>',
           },
           dataType: 'json',
           cache: false,
       })
       .done(function(data){
           $('#memo').val(data.memo);
       })
       .fail(function(data){
       });
   });
</script>