config/routes.rb
Tbsample::Application.routes.draw do
  root :to => 'setofsubyears#index'
  
  match 'auth/:provider/callback' => 'sessions#create'
  match '/logout' => 'sessions#destroy', :as => :logout
  match '/my' => 'sessions#mypage', :as => :mypage

  match 'q/:subject/:year' => 'questions#index'
  match 'q/:subject/:year/:number' => 'questions#show'
  match 'q/:subject/:year/:number/ans/:answer' => 'questions#answer'
  match 'theme/:themecode' => 'themes#index'

  match 'q/:subject/:year/:number/c' => 'comments#index', :via => :get
  match 'q/:subject/:year/:number/c' => 'comments#create', :via => :post, :as => 'question_comments'
  match 'q/:subject/:year/:number/c/new' => 'comments#new'
  match 'q/:subject/:year/:number/c/:id/edit' => 'comments#edit'
  match 'q/:subject/:year/:number/c/:id' => 'comments#update', :via => :put
  match 'q/:subject/:year/:number/c/:id' => 'comments#destroy', :via => :delete

  post 'api/memo' => 'api#set_memo', :as => 'set_memo'
  get 'api/memo' => 'api#get_memo', :as => 'get_memo'

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <% set_meta_tags :site => '中小企業診断士の過去問',
            :description => '中小企業診断士の過去問を年度別、テーマ別で選択できます。',
            :keywords => "中小企業診断士, 過去問, テーマ別, 独学, 勉強法",
            :reverse => true,
            :open_graph => {
                :site_name => '中小企業診断士の過去問',
                :title => 'トップページ',
                :description => '中小企業診断士の過去問を年度別、テーマ別で選択できます。',
                :url => 'http://smec-kakomon.jp/',
                :type => 'website',
                :image => asset_path('logo2.png')
            }
        %>
        <%= content_for?(:meta_tag) ? (content_for :meta_tag) : display_meta_tags %>
                            
        <%= csrf_meta_tags %>
        <%= javascript_include_tag "application" %>

        <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
        <!--[if lt IE 9]>
        <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
        <![endif]-->

        <%= stylesheet_link_tag "application", :media => "all" %>

        <!-- For third-generation iPad with high-resolution Retina display: -->
        <!-- Size should be 144 x 144 pixels -->
        <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

        <!-- For iPhone with high-resolution Retina display: -->
        <!-- Size should be 114 x 114 pixels -->
        <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

        <!-- For first- and second-generation iPad: -->
        <!-- Size should be 72 x 72 pixels -->
        <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

        <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
        <!-- Size should be 57 x 57 pixels -->
        <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

        <!-- For all other devices -->
        <!-- Size should be 32 x 32 pixels -->
        <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    </head>
    <body>
        <div id="fb-root"></div>
        <script>(function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/ja_JP/all.js#xfbml=1&appId=231231420346564";
            fjs.parentNode.insertBefore(js, fjs);
            }(document, 'script', 'facebook-jssdk'));</script>

        <!-- ===== ナビゲーションバー ===== -->
        <div class="navbar navbar-fixed-top navbar-inverse">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="/" style="color: #fefefe">
                        <%= image_tag "/assets/banner_white.png" ,style: "height: 20px" , alt: "smec-kakomon" %>
                    </a>
                    <div class="nav-collapse">
                        <ul class="nav">
                            <li><%= link_to content_tag("i", 'マイページ', {class: "icon-home icon-white"}), mypage_path %></li>
                        </ul>

                        <ul class="nav pull-right">
                            <% if current_user %>
                                <li class="dropdown active">  
                                <a class="dropdown-toggle" role="button" data-toggle="dropdown" data-target="#" href="#">Login as: <%= current_user.name %><b class="caret"></b></a>  
                                <ul class="dropdown-menu">  
                                    <li><%= link_to "ログアウト", logout_path %></li>
                                    <li><p>設定（準備中）</p></li>
                                </ul>  
                                </li> 
                            <% else %>
                                <li class="dropdown active">  
                                <a class="dropdown-toggle" role="button" data-toggle="dropdown" data-target="#" href="#">ログイン<b class="caret"></b></a>  
                                <ul class="dropdown-menu">  
                                    <li><%= link_to "Googleでログイン", login_path_by_google %></li>
                                    <li><%= link_to "twitterでログイン", login_path_by_twitter %></li>
                                    <li><%= link_to "facebookでログイン", login_path_by_facebook %></li>
                                    <!--
                                    <li><%= image_tag "google.png",{style:"display:inline;width:16px"} %><%= link_to "Googleでログイン", login_path_by_google %></li>
                                    <li><%= image_tag "twitter.png" %><%= link_to "twitterでログイン", login_path_by_twitter %></li>
                                    <li><%= image_tag "facebook.png" %><%= link_to "facebookでログイン", login_path_by_facebook %></li>
                                    -->
                                </ul>  
                                </li> 
                            <% end %>
                        </ul>
                    </div>
                </div>
            </div>
        </div>


        <div class="container">
            <% if request.smart_phone? %>
            <% else %>
                <div class="hero-unit">
                    <%= image_tag "/assets/logo2.png", style:"height:150px;float:left; padding-right:30px" ,alt:"logo" %>
                    <h3>中小企業診断士の過去問(β)</h3>
                    <p>ようやくひと通りできました。</p>
                    <p>初めての方はとりあえずログインして年度別に解いてみましょう。</p>
                    <div class="fb-like" data-href="http://smec-kakomon.jp/" data-send="true" data-layout="button_count" data-width="450" data-show-faces="true"></div>
                </div>
            <% end %>
            <div class="row">
                <div class="span9">
                    <% unless session[:user_id] %>
                        <div class="alert alert-info">
                            <button class="close" data-dismiss="alert">&times;</button>
                            ログインすると、学習の履歴が残せます。
                        </div>
                    <% end %>
                    <% if flash[:notice] %>
                        <div class="alert alert-success">
                            <button class="close" data-dismiss="alert">&times;</button>
                            <%= flash[:notice] %>
                        </div>
                     <% elsif flash[:alert] %>
                        <div class="alert alert-error">
                            <button class="close" data-dismiss="alert">&times;</button>
                            <%= flash[:alert] %>
                        </div>
                    <% end %>
                    <%= yield %>
                </div>

                <div class="span3"> <!-- 右カラム -->
                    <div class="sbox">
                        <h2>ユーザー</h2>
                        <div class="sboxInner">
                            <% if current_user %>
                                <p><%= current_user.name %></p>

                            <% else %>
                                <p>ログインしていません</p>
                                <p><%= link_to (image_tag "login_fb.png"), login_path_by_facebook %></p>
                                <p><%= link_to (image_tag "login_tw.png"), login_path_by_twitter %></p>
                                <p><%= link_to (image_tag "google.png",{style:"display:inline;width:32px"})+ "Googleでログイン", login_path_by_google %></p>

                            <% end %>
                        </div>
                    </div>
                    <%= yield :sidebar %>
                </div>
            </div> <!-- 右カラム -->
        <footer>
        <p>&copy; おやつ Company 2013</p>
        </footer>

    </div> <!-- /container -->
    <script type="text/javascript">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-37831503-1']);
        _gaq.push(['_trackPageview']);

        (function() {
         var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
         ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
         var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
         })();

</script>

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

</body>
</html>